alias ..='cd ..'
alias ...='cd ../..'
alias airpln='resetnetworking'
alias bashrc='$EDITOR ~/.bashrc'
alias c='clear'
alias cd..='cd ..'
alias clip='cliphist list | fzf --multi --reverse | cliphist decode | wl-copy'
alias config='quicklaunch_config'
alias configs='quicklaunch_config'
alias die='lock-suspend'
alias die-now='shutdown -P now'
alias dii='lock-suspend'
alias diie='lock-suspend'
alias docu='quicklaunch_documents'
alias documents='quicklaunch_documents'
alias forgive='sudo faillock --user "$USER" --reset'
alias home='cd ~'
alias la='ls -1 -a --color=auto'
alias ll='ls -1 -lh --color=auto'
alias ls='ls --color=auto'
alias note='quicklaunch_notes'
alias notes='quicklaunch_notes'
alias pop='popkitty'
alias proj='quicklaunch_projects'
alias project='quicklaunch_projects'
alias projects='quicklaunch_projects'
alias relaod='source $HOME/.config/shell/bashrc'
alias reload='source $HOME/.config/shell/bashrc'
alias slep='lock-suspend'
alias slip='lock-suspend'
alias srcbash='source $HOME/.config/shell/bashrc'
alias sus='systemctl suspend'
