declare -- BASH="/usr/bin/bash"
declare -r BASHOPTS="checkwinsize:cmdhist:complete_fullquote:expand_aliases:extquote:force_fignore:globasciiranges:globskipdots:hostcomplete:interactive_comments:login_shell:patsub_replacement:progcomp:promptvars:sourcepath"
declare -i BASHPID
declare -- BASHRCSOURCED="Y"
declare -A BASH_ALIASES=()
declare -a BASH_ARGC=([0]="0")
declare -a BASH_ARGV=()
declare -- BASH_ARGV0
declare -A BASH_CMDS=()
declare -- BASH_COMMAND
declare -a BASH_LINENO=()
declare -- BASH_LOADABLES_PATH="/usr/local/lib/bash:/usr/lib/bash:/opt/local/lib/bash:/usr/pkg/lib/bash:/opt/pkg/lib/bash:."
declare -- BASH_MONOSECONDS
declare -a BASH_REMATCH=()
declare -a BASH_SOURCE=()
declare -- BASH_SUBSHELL
declare -ar BASH_VERSINFO=([0]="5" [1]="3" [2]="0" [3]="1" [4]="release" [5]="x86_64-pc-linux-gnu")
declare -- BASH_VERSION="5.3.0(1)-release"
declare -x COLOR_FILE_PATH="/home/Strange/.config/shell/scripts/color-tool/colors.txt"
declare -x COLOR_TOOL_PATH="/home/Strange/.config/shell/scripts/color-tool/color-tool.sh"
declare -- COLUMNS="172"
declare -- COMP_WORDBREAKS
declare -x DBUS_SESSION_BUS_ADDRESS="unix:path=/run/user/1000/bus"
declare -x DEBUGINFOD_URLS="https://debuginfod.archlinux.org "
declare -a DIRSTACK=()
declare -x DISPLAY=":0"
declare -x EDITOR="nvim"
declare -- EPOCHREALTIME
declare -- EPOCHSECONDS
declare -ir EUID="1000"
declare -a FUNCNAME
declare -x GOBIN="/home/Strange/go/bin"
declare -x GOPATH="/home/Strange/go"
declare -a GROUPS=()
declare -i HISTCMD
declare -- HISTFILE="/home/Strange/.bash_history"
declare -- HISTFILESIZE="500"
declare -- HISTSIZE="500"
declare -x HOME="/home/Strange"
declare -- HOSTNAME="Dragonslayer"
declare -- HOSTTYPE="x86_64"
declare -x LANG="C.UTF-8"
declare -x LANGUAGE
declare -x LC_ADDRESS
declare -x LC_COLLATE
declare -x LC_CTYPE
declare -x LC_IDENTIFICATION
declare -x LC_MEASUREMENT
declare -x LC_MESSAGES
declare -x LC_MONETARY
declare -x LC_NAME
declare -x LC_NUMERIC
declare -x LC_PAPER
declare -x LC_TELEPHONE
declare -x LC_TIME
declare -- LINENO
declare -- LINES="35"
declare -x LOGNAME="Strange"
declare -- MACHTYPE="x86_64-pc-linux-gnu"
declare -x MAIL="/var/spool/mail/Strange"
declare -i MAILCHECK="60"
declare -x MOTD_SHOWN="pam"
declare -x OLDPWD="/home/Strange/init-strange/projects/web/draw"
declare -- OPTERR="1"
declare -i OPTIND="1"
declare -- OSTYPE="linux-gnu"
declare -x PATH="/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/home/Strange/.local/bin:/home/Strange/go/bin:/home/Strange/.local/bin:/home/Strange/.local/bin:/home/Strange/go/bin:/home/Strange/.local/bin"
declare -a PIPESTATUS=([0]="0")
declare -ir PPID="36076"
declare -a PROMPT_COMMAND=([0]="__strange_check_interrupt")
declare -- PS1="\\[\\e[0;34m\\]\\W\\[\\e[0;35m\\]\$(parse_git_branch)\\[\\e[0m\\] \\\$ "
declare -- PS2="> "
declare -- PS4="+ "
declare -x PWD="/home/Strange"
declare -i RANDOM
declare -x SDL_VIDEODRIVER="wayland"
declare -- SECONDS
declare -x SHELL="/usr/bin/bash"
declare -r SHELLOPTS="braceexpand:emacs:hashall:histexpand:history:interactive-comments:monitor"
declare -x SHLVL="2"
declare -i SRANDOM
declare -x TERM="tmux-256color"
declare -x TERM_PROGRAM="tmux"
declare -x TERM_PROGRAM_VERSION="3.5a"
declare -x TMUX="/tmp/tmux-1000/default,36076,0"
declare -x TMUX_PANE="%46"
declare -ir UID="1000"
declare -x USER="Strange"
declare -x XDG_CURRENT_DESKTOP="sway"
declare -x XDG_RUNTIME_DIR="/run/user/1000"
declare -x XDG_SEAT="seat0"
declare -x XDG_SESSION_CLASS="user"
declare -x XDG_SESSION_ID="1"
declare -x XDG_SESSION_TYPE="tty"
declare -x XDG_VTNR="1"
declare -- _="-f"
declare -- __STRANGE_SOURCED="1"
declare -- cmd=""
declare -- d="Mood/zen"
declare -- dir=""
declare -a dirs=([0]="Albums" [1]="Artists" [2]="Artists/John_Elton" [3]="Artists/Led_Zeppelin" [4]="Artists/MF_DOOM" [5]="Artists/Miniature_Tigers" [6]="Artists/Misc" [7]="Artists/Pink_Floyd" [8]="Artists/Queens" [9]="Artists/Radiohead" [10]="Artists/Tally_Hall" [11]="Artists/The_Beatles" [12]="Artists/The_Doors" [13]="Artists/The_Rolling_Stones" [14]="Artists/The_Turtles" [15]="Mix" [16]="Mood" [17]="Mood/zen")
declare -- fpath=""
declare -- line=""
declare -a selected=([0]="Artists" [1]="Mood/zen")
declare -a tracks=([0]="Artists/The_Rolling_Stones/3 - Stray Cat Blues (50th Anniversary Edition).mp3" [1]="Artists/The_Rolling_Stones/1 - Ruby Tuesday.mp3" [2]="Artists/The_Rolling_Stones/2 - She’s A Rainbow (Remastered 2017 ⧸ Stereo).mp3" [3]="Artists/Radiohead/26 - Morning Bell⧸Amnesiac.mp3" [4]="Artists/Radiohead/29 - Subterranean Homesick Alien.mp3" [5]="Artists/Radiohead/24 - Radiohead - Sit Down Stand Up.mp3" [6]="Artists/Radiohead/43 - Radiohead - Street Spirit (Fade Out).mp3" [7]="Artists/Radiohead/41 - Bullet Proof ... I Wish I Was.mp3" [8]="Artists/Radiohead/25 - Life In a Glasshouse.mp3" [9]="Artists/Radiohead/27 - Karma Police (Remastered).mp3" [10]="Artists/Radiohead/44 - Ful Stop.mp3" [11]="Artists/Radiohead/28 - Climbing Up the Walls.mp3" [12]="Artists/Radiohead/07 - House Of Cards.mp3" [13]="Artists/Radiohead/18 - How to Disappear Completely.mp3" [14]="Artists/Radiohead/20 - All I Need.mp3" [15]="Artists/Radiohead/04 - Let Down (Remastered).mp3" [16]="Artists/Radiohead/32 - Paranoid Android.mp3" [17]="Artists/Radiohead/39 - Planet Telex.mp3" [18]="Artists/Radiohead/13 - Morning Bell⧸Amnesiac.mp3" [19]="Artists/Radiohead/23 - Myxomatosis.mp3" [20]="Artists/Radiohead/21 - Radiohead - Nude.mp3" [21]="Artists/Radiohead/17 - Radiohead - Burn The Witch.mp3" [22]="Artists/Radiohead/37 - The Bends.mp3" [23]="Artists/Radiohead/12 - Optimistic.mp3" [24]="Artists/Radiohead/38 - Airbag.mp3" [25]="Artists/Radiohead/15 - Dollars and Cents.mp3" [26]="Artists/Radiohead/31 - Fitter Happier.mp3" [27]="Artists/Radiohead/09 - Radiohead - Daydreaming.mp3" [28]="Artists/Radiohead/01 - 2 + 2 = 5.mp3" [29]="Artists/Radiohead/40 - Radiohead - My Iron Lung.mp3" [30]="Artists/Radiohead/03 - Fog.mp3" [31]="Artists/Radiohead/36 - [Nice Dream].mp3" [32]="Artists/Radiohead/08 - Decks Dark.mp3" [33]="Artists/Radiohead/19 - Videotape.mp3" [34]="Artists/Radiohead/05 - Bodysnatchers.mp3" [35]="Artists/Radiohead/34 - Radiohead - High and Dry.mp3" [36]="Artists/Radiohead/16 - You And Whose Army？.mp3" [37]="Artists/Radiohead/14 - Radiohead - Knives Out.mp3" [38]="Artists/Radiohead/33 - Radiohead - Fake Plastic Trees.mp3" [39]="Artists/Radiohead/06 - Weird Fishes ⧸ Arpeggi.mp3" [40]="Artists/Radiohead/11 - Radiohead - Push Pulk ⧸ Spinning Plates.mp3" [41]="Artists/Radiohead/02 - Reckoner.mp3" [42]="Artists/Radiohead/22 - Scatterbrain.mp3" [43]="Artists/Radiohead/30 - Black Star.mp3" [44]="Artists/Radiohead/10 - Life In a Glasshouse.mp3" [45]="Artists/Radiohead/42 - Sulk.mp3" [46]="Artists/Radiohead/35 - Radiohead - Just.mp3" [47]="Artists/The_Beatles/48 - Imagine (Remastered 2010).mp3" [48]="Artists/The_Beatles/30 - The Beatles - Good Day Sunshine.mp3" [49]="Artists/The_Beatles/71 - Eight Days A Week (Remastered 2009).mp3" [50]="Artists/The_Beatles/39 - Got To Get You Into My Life (Remastered 2009).mp3" [51]="Artists/The_Beatles/75 - A Day In The Life (Remix).mp3" [52]="Artists/The_Beatles/34 - The Beatles - Blue Jay Way.mp3" [53]="Artists/The_Beatles/28 - The Beatles - Doctor Robert.mp3" [54]="Artists/The_Beatles/61 - The Beatles - Penny Lane.mp3" [55]="Artists/The_Beatles/17 - Golden Slumbers (2019 Mix).mp3" [56]="Artists/The_Beatles/55 - Only A Northern Song (Remastered 2009).mp3" [57]="Artists/The_Beatles/10 - Ticket To Ride (Remastered 2009).mp3" [58]="Artists/The_Beatles/54 - The Beatles - Hey Bulldog (Promo video).mp3" [59]="Artists/The_Beatles/24 - Carry That Weight (2019 Mix).mp3" [60]="Artists/The_Beatles/04 - Back In The U.S.S.R. (Remastered 2009).mp3" [61]="Artists/The_Beatles/45 - The Beatles - I'm Only Sleeping.mp3" [62]="Artists/The_Beatles/64 - Being For The Benefit Of Mr. Kite! (Remix).mp3" [63]="Artists/The_Beatles/40 - The Beatles - Tomorrow Never Knows.mp3" [64]="Artists/The_Beatles/67 - Yellow Submarine (Highlighted Sound Effects).mp3" [65]="Artists/The_Beatles/69 - Strawberry Fields Forever (Remastered 2009).mp3" [66]="Artists/The_Beatles/09 - Mind Games (Ultimate Mix).mp3" [67]="Artists/The_Beatles/13 - Woman (Remastered 2010).mp3" [68]="Artists/The_Beatles/70 - A Day In The Life (Remastered 2017).mp3" [69]="Artists/The_Beatles/07 - Sexy Sadie (Remastered 2009).mp3" [70]="Artists/The_Beatles/12 - Instant Karma! (We All Shine On) (Ultimate Mix).mp3" [71]="Artists/The_Beatles/73 - Within You Without You (Remix).mp3" [72]="Artists/The_Beatles/31 - The Beatles - She Said She Said.mp3" [73]="Artists/The_Beatles/41 - The Beatles - I Want To Tell You.mp3" [74]="Artists/The_Beatles/38 - Baby, You're A Rich Man (Remastered 2009).mp3" [75]="Artists/The_Beatles/01 - While My Guitar Gently Weeps (Remastered 2009).mp3" [76]="Artists/The_Beatles/15 - The Ballad Of John And Yoko (Remastered 2009).mp3" [77]="Artists/The_Beatles/18 - Mean Mr Mustard (2019 Mix).mp3" [78]="Artists/The_Beatles/29 - The Beatles - And Your Bird Can Sing.mp3" [79]="Artists/The_Beatles/22 - I Want You (She's So Heavy) (2019 Mix).mp3" [80]="Artists/The_Beatles/33 - Flying (Remastered 2009).mp3" [81]="Artists/The_Beatles/23 - Octopus's Garden (2019 Mix).mp3" [82]="Artists/The_Beatles/66 - Sgt. Pepper's Lonely Hearts Club Band (Remix).mp3" [83]="Artists/The_Beatles/16 - The Long And Winding Road (Remastered 2009).mp3" [84]="Artists/The_Beatles/37 - All You Need Is Love (Remastered 2009).mp3" [85]="Artists/The_Beatles/14 - Old Brown Shoe (Remastered 2009).mp3" [86]="Artists/The_Beatles/49 - Till There Was You (Remastered 2009).mp3" [87]="Artists/The_Beatles/51 - The Beatles - Something.mp3" [88]="Artists/The_Beatles/60 - Lucy In The Sky With Diamonds (Remastered 2009).mp3" [89]="Artists/The_Beatles/21 - Because (2019 Mix).mp3" [90]="Artists/The_Beatles/43 - The Beatles - Here, There and Everywhere.mp3" [91]="Artists/The_Beatles/35 - Your Mother Should Know (Remastered 2009).mp3" [92]="Artists/The_Beatles/19 - Sun King (2019 Mix).mp3" [93]="Artists/The_Beatles/44 - The Beatles - Love You To.mp3" [94]="Artists/The_Beatles/65 - With A Little Help From My Friends (Remix).mp3" [95]="Artists/The_Beatles/47 - The Beatles - Taxman.mp3" [96]="Artists/The_Beatles/42 - The Beatles - For No One.mp3" [97]="Artists/The_Beatles/05 - Cry Baby Cry (Remastered 2009).mp3" [98]="Artists/The_Beatles/32 - The Fool On The Hill (Remastered 2009).mp3" [99]="Artists/The_Beatles/58 - I Am The Walrus (Remastered 2009).mp3" [100]="Artists/The_Beatles/57 - Get Back (Remastered 2009).mp3" [101]="Artists/The_Beatles/56 - Across The Universe (Remastered 2009).mp3" [102]="Artists/The_Beatles/50 - The Beatles - Let It Be.mp3" [103]="Artists/The_Beatles/20 - You Never Give Me Your Money (2019 Mix).mp3" [104]="Artists/The_Beatles/74 - When I'm Sixty-Four (Remix).mp3" [105]="Artists/The_Beatles/25 - Maxwell's Silver Hammer (2019 Mix).mp3" [106]="Artists/The_Beatles/62 - Lovely Rita (Remix).mp3" [107]="Artists/The_Beatles/03 - Julia (Remastered 2009).mp3" [108]="Artists/The_Beatles/53 - The Beatles - Here Comes The Sun (2019 Mix).mp3" [109]="Artists/The_Beatles/36 - The Beatles - Hello, Goodbye.mp3" [110]="Artists/The_Beatles/02 - Getting Better (Remix).mp3" [111]="Artists/The_Beatles/46 - The Beatles - Eleanor Rigby (From ＂Yellow Submarine＂).mp3" [112]="Artists/The_Beatles/08 - Watching The Wheels (Remastered 2010).mp3" [113]="Artists/The_Beatles/26 - Working Class Hero (Remastered 2010).mp3" [114]="Artists/The_Beatles/11 - Ob-La-Di, Ob-La-Da (Remastered 2009).mp3" [115]="Artists/The_Beatles/59 - The Beatles - Lady Madonna.mp3" [116]="Artists/The_Beatles/72 - Fixing A Hole (Remix).mp3" [117]="Artists/The_Beatles/63 - She's Leaving Home (Remix).mp3" [118]="Artists/The_Beatles/06 - Dear Prudence (Remastered 2009).mp3" [119]="Artists/The_Beatles/68 - Hey Jude (Remastered 2009).mp3" [120]="Artists/The_Beatles/27 - [Just Like] Starting Over (Remastered 2010).mp3" [121]="Artists/The_Beatles/52 - The Beatles - Come Together.mp3" [122]="Artists/Led_Zeppelin/1 - Going to California (Remaster).mp3" [123]="Artists/Led_Zeppelin/2 - Black Dog (Remaster).mp3" [124]="Artists/Tally_Hall/05 - The Bidding.mp3" [125]="Artists/Tally_Hall/04 - Taken for a Ride.mp3" [126]="Artists/Tally_Hall/03 - Cannibal.mp3" [127]="Artists/Tally_Hall/02 - Joe Hawley - IX. Aristotle's Denial.mp3" [128]="Artists/Tally_Hall/11 - The Trap.mp3" [129]="Artists/Tally_Hall/13 - Hymn for a Scarecrow.mp3" [130]="Artists/Tally_Hall/10 - &.mp3" [131]="Artists/Tally_Hall/07 - Two Wuv.mp3" [132]="Artists/Tally_Hall/01 - Special - Joe Hawley. [Joe Hawley Joe Hawley] [Rap part removed.].mp3" [133]="Artists/Tally_Hall/06 - Banana Man.mp3" [134]="Artists/Tally_Hall/09 - Joe Hawley - Aristotle's Denial Official Video (Unreversed).mp3" [135]="Artists/Tally_Hall/12 - Just Apathy.mp3" [136]="Artists/Tally_Hall/08 - Spring and a Storm.mp3" [137]="Artists/Miniature_Tigers/7 - Hot Venom.mp3" [138]="Artists/Miniature_Tigers/6 - Bullfighter Jacket.mp3" [139]="Artists/Miniature_Tigers/1 - Rock N' Roll Mountain Troll.mp3" [140]="Artists/Miniature_Tigers/3 - Egyptian Robe.mp3" [141]="Artists/Miniature_Tigers/2 - Mansion of Misery.mp3" [142]="Artists/Miniature_Tigers/4 - Japanese Woman Living in My Closet.mp3" [143]="Artists/Miniature_Tigers/5 - Tropical Birds.mp3" [144]="Artists/Miniature_Tigers/8 - Boomerang.mp3" [145]="Artists/Misc/03 - Virtual Insanity (Remastered 2013).mp3" [146]="Artists/Misc/26 - I Am a Child (2017 Remaster).mp3" [147]="Artists/Misc/25 - Night Bird Flying.mp3" [148]="Artists/Misc/02 - Louie Louie.mp3" [149]="Artists/Misc/22 - Scarborough Fair ⧸ Canticle.mp3" [150]="Artists/Misc/04 - El Muchacho de los Ojos Tristes.mp3" [151]="Artists/Misc/11 - Washing Machine Heart.mp3" [152]="Artists/Misc/30 - Orange Peel.mp3" [153]="Artists/Misc/29 - Mrs. Robinson (From ＂The Graduate＂ Soundtrack).mp3" [154]="Artists/Misc/09 - Hope.mp3" [155]="Artists/Misc/07 - John, Take Me with You.mp3" [156]="Artists/Misc/12 - Hit the Road Jack.mp3" [157]="Artists/Misc/21 - Dark Red.mp3" [158]="Artists/Misc/28 - Dream A Little Dream Of Me.mp3" [159]="Artists/Misc/10 - Can't Get You out Of My Head.mp3" [160]="Artists/Misc/19 - Daydream.mp3" [161]="Artists/Misc/01 - The Island.mp3" [162]="Artists/Misc/23 - People Are Strange (New Stereo Mix).mp3" [163]="Artists/Misc/27 - Twentieth Century Fox (New Stereo Mix).mp3" [164]="Artists/Misc/20 - aNTOJE - 3 Koopa Kingz.mp3" [165]="Artists/Misc/05 - A Human's Touch.mp3" [166]="Artists/Misc/14 - Seven Nation Army.mp3" [167]="Artists/Misc/34 - Paper Planes.mp3" [168]="Artists/Misc/13 - Pumped Up Kicks.mp3" [169]="Artists/Misc/16 - Huit octobre 1971.mp3" [170]="Artists/Misc/06 - Hey Lover!.mp3" [171]="Artists/Misc/31 - Tell Me Why.mp3" [172]="Artists/Misc/18 - The House of the Rising Sun.mp3" [173]="Artists/Misc/33 - Smoke Rings.mp3" [174]="Artists/Misc/08 - Peter McPoland - Digital Silence (.mp4).mp3" [175]="Artists/Misc/17 - Feel It Still.mp3" [176]="Artists/Misc/15 - Deceptacon.mp3" [177]="Artists/Misc/32 - When You Dance I Can Really Love.mp3" [178]="Artists/Misc/24 - Wishful Sinful.mp3" [179]="Artists/The_Doors/1 - Touch Me (Doors Only Mix) (Robby Krieger Overdub).mp3" [180]="Artists/The_Doors/3 - People Are Strange (New Stereo Mix).mp3" [181]="Artists/The_Doors/2 - Twentieth Century Fox (New Stereo Mix).mp3" [182]="Mood/zen/12 - Jake Chudnow - Dustin Grieber.mp3" [183]="Mood/zen/14 - Jake Chudnow - Turquoise.mp3" [184]="Mood/zen/01 - Dayvan Cowboy.mp3" [185]="Mood/zen/07 - Jake Chudnow - Natty Sci.mp3" [186]="Mood/zen/08 - Jake Chudnow - Strange White Ocean Motion.mp3" [187]="Mood/zen/10 - ＂Transition 1＂ by Jake Chudnow [HD].mp3" [188]="Mood/zen/16 - Birds.mp3" [189]="Mood/zen/03 - Aquarius.mp3" [190]="Mood/zen/13 - ＂126＂ by Jake Chudnow [HD] (2006, Original Version).mp3" [191]="Mood/zen/02 - Chromakey Dreamcoat.mp3" [192]="Mood/zen/04 - Everything You Do Is A Balloon.mp3" [193]="Mood/zen/15 - ＂For Leah＂ by Jake Chudnow [HD].mp3" [194]="Mood/zen/06 - ＂Moan＂ by Jake Chudnow [HD].mp3" [195]="Mood/zen/11 - Jake Chudnow - Watch a Tiny House.mp3" [196]="Mood/zen/05 - Jake Chudnow - It's Good to Be D.mp3" [197]="Mood/zen/09 - Jake Chudnow - Half a Dozen Bullets.mp3")
